### ISSUE TITLE
problem during assembly

### ISSUE THREAD

**Issue by chrisdiebolder** [marcinsaj/IN12-IN15-Binary-Nixie-Clock#1]
Hi Marcin,
absulutely loving this project! Though I am facing an issue during assembly: How is it possible to place all the 126 pins (page 10 of assembly instruction) in a way that the PCB slides over it? I was fiddling around for quite a while concluding that it is close to impossible to have them all  positioned accurately enough. Is there any trick?

Best,
Chris

**Comment by marcinsaj** [comment]
@chrisdiebolder 
You probably received pins with a larger diameter at the base, which is why it makes assembly difficult. Try to do it in batches, e.g. one row at a time.

**Comment by chrisdiebolder** [comment]
Ok thanks, I will try batchwise. Also ordered some thinner pins as backup.

**Comment by chrisdiebolder** [comment]
Update: took me a while and quite some patience, but finally got it working :)

**Comment by marcinsaj** [comment]
I’m glad you figured it out.
